/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audio` | `/audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/story/._[id]`; params?: Router.UnknownInputParams; } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/courses/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/courses/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/audio` | `/audio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/story/._[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `/story/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/courses/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/courses/lesson/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/audio${`?${string}` | `#${string}` | ''}` | `/audio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/story/._[id]${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audio` | `/audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/story/._[id]`; params?: Router.UnknownInputParams; } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | `/story/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/courses/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/courses/lesson/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/courses/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/courses/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
